/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "notify.h"

void notify_prog_1(char* host)
{
    CLIENT* clnt;
    char** result_1;
    char* notify_1_arg;
    clnt = clnt_create(host, NOTIFY_PROG, NOTIFY_VERS, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror(host);
        exit(1);
    }
    result_1 = notify_1(&notify_1_arg, clnt);
    if (result_1 == NULL) {
        clnt_perror(clnt, "call failed:");
    }
    clnt_destroy(clnt);
}

main(int argc, char* argv[])
{
    char* host;

    if (argc < 2) {
        printf("usage: %s server_host\n", argv[0]);
        exit(1);
    }
    host = argv[1];
    notify_prog_1(host);
}
