/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: notify.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "notify.pb-c.h"
void   notify__test__init
                     (Notify__Test         *message)
{
  static Notify__Test init_value = NOTIFY__TEST__INIT;
  *message = init_value;
}
size_t notify__test__get_packed_size
                     (const Notify__Test *message)
{
  assert(message->base.descriptor == &notify__test__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t notify__test__pack
                     (const Notify__Test *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &notify__test__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t notify__test__pack_to_buffer
                     (const Notify__Test *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &notify__test__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Notify__Test *
       notify__test__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Notify__Test *)
     protobuf_c_message_unpack (&notify__test__descriptor,
                                allocator, len, data);
}
void   notify__test__free_unpacked
                     (Notify__Test *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &notify__test__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor notify__test__field_descriptors[4] =
{
  {
    "program",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Notify__Test, program),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Notify__Test, version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "method",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Notify__Test, method),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "str",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Notify__Test, str),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned notify__test__field_indices_by_name[] = {
  2,   /* field[2] = method */
  0,   /* field[0] = program */
  3,   /* field[3] = str */
  1,   /* field[1] = version */
};
static const ProtobufCIntRange notify__test__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor notify__test__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "notify.test",
  "Test",
  "Notify__Test",
  "notify",
  sizeof(Notify__Test),
  4,
  notify__test__field_descriptors,
  notify__test__field_indices_by_name,
  1,  notify__test__number_ranges,
  (ProtobufCMessageInit) notify__test__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor notify__notify_service__method_descriptors[1] =
{
  { "Notify", &notify__test__descriptor, &notify__test__descriptor },
};
const unsigned notify__notify_service__method_indices_by_name[] = {
  0         /* Notify */
};
const ProtobufCServiceDescriptor notify__notify_service__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "notify.NotifyService",
  "NotifyService",
  "Notify__NotifyService",
  "notify",
  1,
  notify__notify_service__method_descriptors,
  notify__notify_service__method_indices_by_name
};
void notify__notify_service__notify(ProtobufCService *service,
                                    const Notify__Test *input,
                                    Notify__Test_Closure closure,
                                    void *closure_data)
{
  assert(service->descriptor == &notify__notify_service__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void notify__notify_service__init (Notify__NotifyService_Service *service,
                                   Notify__NotifyService_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &notify__notify_service__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
