// Code generated by protoc-gen-go.
// source: notify.proto
// DO NOT EDIT!

/*
Package notify is a generated protocol buffer package.

It is generated from these files:
	notify.proto

It has these top-level messages:
	Test
*/
package notify

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Test struct {
	Program          *int32  `protobuf:"varint,1,req,name=program" json:"program,omitempty"`
	Version          *int32  `protobuf:"varint,2,req,name=version" json:"version,omitempty"`
	Method           *int32  `protobuf:"varint,3,req,name=method" json:"method,omitempty"`
	Str              *string `protobuf:"bytes,4,req,name=str" json:"str,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Test) Reset()                    { *m = Test{} }
func (m *Test) String() string            { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()               {}
func (*Test) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Test) GetProgram() int32 {
	if m != nil && m.Program != nil {
		return *m.Program
	}
	return 0
}

func (m *Test) GetVersion() int32 {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return 0
}

func (m *Test) GetMethod() int32 {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return 0
}

func (m *Test) GetStr() string {
	if m != nil && m.Str != nil {
		return *m.Str
	}
	return ""
}

func init() {
	proto.RegisterType((*Test)(nil), "notify.test")
}

var fileDescriptor0 = []byte{
	// 132 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0xcb, 0x2f, 0xc9,
	0x4c, 0xab, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x5c, 0xb9, 0x58,
	0x4a, 0x52, 0x8b, 0x4b, 0x84, 0xf8, 0xb9, 0xd8, 0x81, 0x12, 0xe9, 0x45, 0x89, 0xb9, 0x12, 0x8c,
	0x0a, 0x4c, 0x1a, 0xac, 0x20, 0x81, 0xb2, 0xd4, 0xa2, 0xe2, 0xcc, 0xfc, 0x3c, 0x09, 0x26, 0xb0,
	0x00, 0x1f, 0x17, 0x5b, 0x6e, 0x6a, 0x49, 0x46, 0x7e, 0x8a, 0x04, 0x33, 0x98, 0xcf, 0xcd, 0xc5,
	0x5c, 0x5c, 0x52, 0x24, 0xc1, 0x02, 0xe4, 0x70, 0x1a, 0x99, 0x72, 0xf1, 0xfa, 0x81, 0x0d, 0x0c,
	0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x15, 0x52, 0xe1, 0x62, 0x83, 0x08, 0x08, 0xf1, 0xe8, 0x41,
	0x2d, 0x06, 0xd9, 0x23, 0x85, 0xc2, 0x03, 0x04, 0x00, 0x00, 0xff, 0xff, 0x2e, 0xdd, 0xb6, 0x16,
	0x94, 0x00, 0x00, 0x00,
}
